### ISSUE TITLE
Application architecture

### ISSUE THREAD

**Issue by craciunescu** [ubiqcomp/capacity#10]
Comentar el funcionamiento en conjunto y organización de la arquitectura de la aplicación.

Este issue depende de #6 y de #5

**Comment by HernandezIgnacio** [comment]
To reach our objectives during the development of this application we will be using a **4 layer architecture**: 
 + <u>**Perception Layer:**</u> For this layer we will use an **Arduino motherboard**, attached to a number of **sensors**, which will be registering all the information given by the **practice model**.
 + <u>**Network Layer:**</u> This is in charge of connecting the **sensors** to the **processing layer** in order to process all the data taken by them. **Wifi** connection will be mostly used in this layer.
 + <u>**Processing Layer:**</u> This layer will consist of the following components: 
   + **<u>MQTT broker:</u>**  **Mosquitto**, that will be managing all the incoming and outgoing messages.
   + **<u>Server:</u>** Here is where we will save all the collected information by the **perception layer**. To host this **server** we will use **Apache Tomcat**
   + **<u>Database:</u>**  This **database** will allow us to manage and process the information. 
 + <u>**Application Layer:**</u> This last component of the architecture will be composed of a **mobile application**. This **application** will allow the users to access the information on the **server**.

**Comment by HernandezIgnacio** [comment]
Me faltaría detallar un poco la processing layer, que como juraría que no hemos hablado de lo que vamos a hacer ahí me he guiado un poco por el ejemplo de proyecto que hay colgado en BB. Una vez lo hablemos, y si no hay nada más que modificar, lo rehago y este issue ya se podría dar por terminado.

**Comment by craciunescu** [comment]
Conceptualmente lo veo bastante bien.

Te propongo un par de mejoras super simples:
- [ ] Describirlo en una imagen (te adjunto la misma imagen que te he puesto en otro issue como un ejemplo)
![Screenshot 2020-11-18 at 17 34 05](https://user-images.githubusercontent.com/25935100/99559626-494cd400-29c5-11eb-8fa5-f37559b5b903.png)
- [ ] Definir un poco más los componentes. En vez de decir Arduino motherboard, por ejemplo, hablemos para ver qué modelo en concreto. Eso también depende de los demás pero evidentemente es un elemento importante.
- [ ] ¿Qué lenguajes de programación emplearíamos para todo esto? Yo tengo comodidad con prácticamente todo, pero cada uno tiene su situación particular. Asegurémonos de que lo hacemos con algo que todo el mundo tiene medio dominado.

Si le añades esas cosas a lo que ya tienes hecho considero que está perfecto. Redáctalo para que quede bonito en un documento y lo cogemos tal cual y añadimos a la memoria. Salu²

**Comment by HernandezIgnacio** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/58726539/99683812-08b29080-2a81-11eb-9817-215730b314ae.png)

**Comment by craciunescu** [comment]
Te ha quedado tremendo. Escríbete un pequeño párrafo describiendo cada cosa, haz un pull request y por mí está perfecto.

**Comment by ZainAzhar** [comment]
esa imagen tambien valdria para #6 tecnología a utilizar

**Comment by HernandezIgnacio** [comment]
![Untitled Diagram (1)](https://user-images.githubusercontent.com/58726539/99708148-b6cc3380-2a9d-11eb-93a6-fa5f4ab35d9c.png)

**Comment by HernandezIgnacio** [comment]
![Untitled Diagram (1) (1)](https://user-images.githubusercontent.com/58726539/99716521-8211a980-2aa8-11eb-94fe-2e628116f295.png)

**Comment by craciunescu** [comment]
Tal vez meter nombres a los componentes nos venga bien, dudo que los profesores sepan lo que es con solo verlo hahhaha

**Comment by HernandezIgnacio** [comment]
![Untitled Diagram (1) (1) (1) (1)](https://user-images.githubusercontent.com/58726539/99719332-745e2300-2aac-11eb-8678-25dfc4669c60.png)
